project:
  type: website
  output-dir: docs

website:
  title: "Jenny's E-Portfolio"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: projects/index.qmd
        text: ML Project
      - href: cv.qmd
        text: Curriculum Vitae
      - href: reflection.qmd
        text: Reflection
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: 
      light: lux
      dark: darkly
    css: styles.scss
    toc: true
    code-fold: true
    code-tools: true
