project:
  type: website
  output-dir: docs

website:
  title: "Jenny's E-Portfolio"
  favicon: images/fav.png
  navbar:
    logo: images/log.png
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects/index.qmd
        text: Projects
      - href: cv.qmd
        text: Curriculum Vitae
        target: _blank
      - href: reflection.qmd
        text: Reflection
      - href: contact.qmd
        text: Contact
    right:
      - href: https://github.com/JennyHoeglauer
        text: GitHub
        target: _blank

  page-footer:
    center: "© 2025 Jenny Höglauer | Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      light: lux
      dark: darkly
    css: styles.scss
    toc: true
    code-fold: true
    code-tools: true
